public with sharing class DraftArticle extends AbstractArticle {

    public int myMethod () {
        while(true){
        }

        for(Accts newAcct : listAccts){
        }
    }

    public DraftArticle(){
            insert newAcct;
    }

    @deprecated    
    public void myInit(){
        int max = 10;
    }

    @isTest public void testType() {
        System.assert(true);
        System.assertEquals('name', 'name');
    }

}


    